### ISSUE TITLE
js怎么渲染script标签引入的子模板

### ISSUE THREAD

**Issue by LikeDege** [byends/art-template-loader#11]
```
import InstallmentTpl from '../art/huabeiInstallment.tpl'


let creditPayInfoList = {
    list: [1, 3, 3]
}
let html = InstallmentTpl('模板名称', {creditPayInfoList})
```

这样是不行的

**Comment by visamz** [comment]
如果你是用script inline 方式引入的，那就不需要用到这个 loader 了，你直接引入`artTemplate` 引擎即可，具体使用可查看官方文档，当然，这里 `demo`文件里也有例子

**Comment by LikeDege** [comment]
@byends 额，我就是用webpack把tpl预编译了，子模板也用script写在这个tpl里，预编译后怎么写？

**Comment by visamz** [comment]
这个`loader` 不支持模板嵌套

**Comment by LikeDege** [comment]
@byends 能支持下吗？

**Comment by visamz** [comment]
这个不好实现，你可以直接拆分成两个 `tpl` 引入

**Comment by LikeDege** [comment]
@byends 不是用tmodjs做预编译吗？只是一个业务弹窗所以不大想拆开

**Comment by visamz** [comment]
不是tmodjs

**Comment by LikeDege** [comment]
@byends 额，好绝望

**Comment by visamz** [comment]
这有啥啊，你拆成两个 tpl 有什么 影响啊。。。。

**Comment by LikeDege** [comment]
@byends 有很多这种子模板，我不想建太多的文件和文件夹。还有还不能支持include按路径嵌入tpl。

**Comment by visamz** [comment]
那你干脆把模板都 inline 进页面，不需要预编译

**Comment by LikeDege** [comment]
@byends 框架已经定下来用art-template-loader了，预编译也是必要的

**Comment by visamz** [comment]
你这相矛盾。。只要用了 inline 方式，就是绕过了预编译了

**Comment by visamz** [comment]
一部份编译，一部份绕过，你调试起来 也很累啊

**Comment by LikeDege** [comment]
@byends 我的想法就是全部预编译，你说的是scprit inline然后不预编译吗？这样不是更麻烦，我再想想其他办法吧，唉。

**Comment by visamz** [comment]
对，`scprit inline` 这种方式是不能预编译的

**Comment by LikeDege** [comment]
@byends 你能不能参考下tmodjs？我以为能支持，这下难搞了

**Comment by visamz** [comment]
暂不能支持
