### ISSUE TITLE
请求转让 npm 包

### ISSUE THREAD

**Issue by aui** [byends/art-template-loader#12]
hi, 我是 art-template 的作者，非常感谢你给 art-template 增加了 webpack loader 的支持！

art-template 发布了 v4.0.0 beta 版本，正准备重新开发 webpack loader，不知是否方便将 npm 包转让给我，以便 art-template 与周边插件的发布能够借助 CI 统一发版本。

**Comment by visamz** [comment]
更要感觉你开发这个强大的模板引擎！
愿意转让，如何操作呢？

**Comment by aui** [comment]
<https://www.npmjs.com/package/art-template-loader/access>

**Comment by visamz** [comment]
已添加

**Comment by aui** [comment]
感谢！新的 loader 计划支持所有 art-template 的特性，尤其是子模板支持。请关注持续更新：<https://github.com/aui/art-template-loader>
