### ISSUE TITLE
请问一下有处理 tpl 中 img 的 src 问题吗。。。。

### ISSUE THREAD

**Issue by zwlcoding** [byends/art-template-loader#6]

**Comment by visamz** [comment]
什么问题？说具体点啊

**Comment by zwlcoding** [comment]
抱歉，当时没写明白，因为项目的一些原因

比如我有一个 tpl 文件, 开发的时候图片资源路径写的相对路径

`  <div class="act-item"> <img src="../static/pic_01.jpg"></div>`

但是正是上线的时候需要改成

`  <div class="act-item"> <img src="//xx.test.com/static/pic_01.jpg"></div>`

正常可以通过配置 webpack 的 output.path 来处理，但是 模板文件 中好像没有特别好的处理方式？

**Comment by visamz** [comment]
这个目前没有办法，你可以在 代码里定义一个 常量，传进 模板里渲染
