### ISSUE TITLE
作为HtmlWebpackPlugin的模板会报错

### ISSUE THREAD

**Issue by LikeDege** [byends/art-template-loader#9]
不好意思，我再提个问题，用art-template-loader作为HtmlWebpackPlugin时会报错，错误如下

webpack配置如下

```
module: {
    rules: [
      {
        test: /\.tpl$/,
        loader: 'art-template-loader'
      }
｝,
plugins: [
  new HtmlWebpackPlugin({
        title: 'test',
        filename: '/test.html',
        template: 'index.tpl',
        inject: true,
        chunks: ['vendor', 'test'],
        chunksSortMode: 'dependency',
        bodyContent: '<div>test</div>'
  })
]

```

index.tpl 如下

```
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{ htmlWebpackPlugin.options.title }}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width">
    <meta name="format-detection" content="telephone=no">
</head>
<body>
  <div id="app">{{ htmlWebpackPlugin.options.bodyContent }}</div>
</body>
</html>
```

`ERROR in   Error: Expected html to be a string but got "<!DOCTYPE html>\r\n<html lang=\"e  n\">\r\n<head>\r\n    <title>test</title>\r\n    <meta charset=\"utf-8\">\r\n      <meta name=\"viewport\" content=\"initial-scale=1, maximum-scale=1, user-sca  lable=no, width=device-width\">\r\n    <meta name=\"format-detection\" content  =\"telephone=no\">\r\n</head>\r\n<body>\r\n  <div id=\"app\">&#60;div&#62;test  &#60;/div&#62;</div>\r\n</body>\r\n</html>"`

麻烦看一下是否loader的问题，因为我试了下ejs-loader可以这样用

**Comment by visamz** [comment]
art-template 是js 模板引擎，你搞错了。 htmlwebpackplugin 是 html 模板

**Comment by LikeDege** [comment]
@byends ejs也是类似于art-template的js模板引擎

**Comment by visamz** [comment]
htmlwebpackplugin 有自己的语法，并不是使用了 ejs，只是可能刚好语法一致

**Comment by visamz** [comment]
不过，我看到，确认是有解析的，只是这报错一时没看出来啥原因

**Comment by visamz** [comment]
不过，你这用法也是挺奇怪的，为什么会这样使用呢

**Comment by LikeDege** [comment]
@byends 因为我想webpack打包也用同一个模板，然后一些组件可以复用，不过art-template貌似不能实现组件复用，include指令不能按路径找.tpl文件

**Comment by LikeDege** [comment]
@byends 不过这里我觉得应该可以作为HtmlWebpackPlugin的模板，有空的话可以参考下ejs-loader

**Comment by LikeDege** [comment]
@byends 在art-template最后输出时不转成String类型就可以了，不大理解为什么要转成String类型
